services:
  - type: web
    name: resume-analyzer-backend
    env: node
    plan: free
    rootDirectory: backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/resumes/test
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://resume-analysis-two.vercel.app,http://localhost:3000
      - key: DATABASE_URL
        fromDatabase:
          name: resume-analyzer-db
          property: connectionString

  - type: postgres
    name: resume-analyzer-db
    plan: free
    databaseName: resume_analyzer
    user: resume_user

